import type { Metadata } from "next";
import { IBM_Plex_Sans, Inter } from "next/font/google";
import "./globals.css";
<<<<<<< Updated upstream
import { Providers } from "./providers";
=======
import {Providers} from "./providers";
>>>>>>> Stashed changes

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{  children: React.ReactNode;}>) {
  return (
<<<<<<< Updated upstream
    <html lang="en" className={ibmPlexSans.className}suppressHydrationWarning>
      <body className={inter.className}>{children}</body>
=======
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
>>>>>>> Stashed changes
    </html>
  );
}
